obj-$(CONFIG_OPPO_COMMON_SOFT)	+=  oppo_project/
obj-$(CONFIG_OPPO_DEVICE_IFNO)	+=  oppo_devinfo/
#ifdef CONFIG_PRODUCT_REALME_RMX1801
#//jie.cheng@swdh.sh, 2016/04/15, Add hypnus helper
obj-y     +=  oppo_hypnus/
#endif /* CONFIG_PRODUCT_REALME_RMX1801 */
#ifdef CONFIG_PRODUCT_REALME_RMX1801
#//wenbin.liu@PSW.Kernel.MM, 2018/05/23, Add for Healthinfo monitor
obj-y     +=  oppo_healthinfo/
#endif /* CONFIG_PRODUCT_REALME_RMX1801 */
